@startuml Pizzaria
title Sistema de controle de pedidos de uma pizzaria delivery

class Cliente {
    - idCliente: Int
    - nome: String
    - telefone: String
    - bairro: String
    + cadastrarCliente()
    + alterarCliente()
    + excluirCliente()
}

class Atendente {
    - idAtendente: Int
    - nome: String
    + cadastrarAtendente()
    + alterarAtendente()
    + excluirAtendente()
}

class Pedido {
    - idPedido: Int
    - data: Date
    - hora: Time
    - status : String
    + cadastrarPedido()
    + alterarPedido()
    + excluirPedido()
}

class ItemPedido {
    - idItemPedido: Int
    - quantidade: Int
    - desc : String
    + cadastrarItemPedido()
    + alterarItemPedido()
    + excluirItemPedido()
}

class ItemCardapio {
    - idItemCardapio: Int
    - nome: String
    - descricao: String
    - preco: Double
    + cadastrarItemCardapio()
    + alterarItemCardapio()
    + excluirItemCardapio()
}

class Cardapio {
    - idCardapio: Int
    - nome: String
    + alterarCardapio()
    + excluirCardapio()
}

Cliente "1:1" -- "0..*" Pedido: "realiza"
Pedido "0..*" -- "1:1" Atendente: "cadastra"
Pedido "1:1" -- "1..*" ItemPedido: "contém"
ItemPedido "1:1" -- "1..*" ItemCardapio: "é composto por"
Cardapio "1:1" -- "1..*" ItemCardapio: "contém"

@enduml