@startuml Anotar Pedido
title Anotar Pedido
actor Atendente
entity Sistema
database BancoDeDados

Atendente -> Sistema: Insere os dados do cliente
Sistema -> BancoDeDados: Verifica se o cliente já existe
BancoDeDados -> Sistema: Se o cliente já existe, redireciona para a pagina de cadastro de pedidos
Sistema -> BancoDeDados: Cadastra o cliente (se novo)
Sistema -> Sistema: Armazena dados do cliente
Atendente -> Sistema: Insere os itens do pedido (sabor, tamanho, quantidade)
Sistema -> BancoDeDados: Cadastra o pedido no banco de dados e direciona para a pagina de resumo do pedido


alt Fluxo Alternativo
    Atendente -> Sistema: Cancela o pedido
end

alt Pontos de Extensão
    Atendente -> Sistema: Anota observações do cliente
    Atendente -> Sistema: Anota a forma de pagamento
end

@enduml