@startuml Loga Sistema
title Loga Sistema
actor Atendente
entity Sistema
database BancoDeDados

Atendente -> Sistema: Insere login e senha
Sistema -> BancoDeDados: Verifica credenciais
BancoDeDados -> Sistema: Retorna credenciais válidas
Sistema -> Atendente: Exibe tela principal

alt Fluxo Alternativo
    Sistema -> Atendente: Credenciais inválidas
    Sistema -> Atendente: Exibe mensagem de erro
end

@enduml